### PR TITLE
Actual sunrise/sunset times

### PR DESCRIPTION
**Pull request by MikeBishop**
Rather than using the intentionally broad 6 AM to 8 PM defaults, this adds a scheduled task to fetch local sunrise/sunset times daily and use them.  (But still only to hour precision, because changing that is harder.)  In case of any failure, it should fall back to the existing default.

### CODE REVIEW

**Comment by MikeBishop** [comment]
@ngardiner, could you run with this on your system for a while?  It works for me, but I'd like to ensure it doesn't step on anything else.  Also, the tests appear not to be running, so I'll defer to your okay on that.

**Comment by ngardiner** [comment]
will do @MikeBishop.

**Comment by MikeBishop** [comment]
@ngardiner, this seems to be working fine for me.  As you haven't mentioned any issues with it, I'll go ahead and merge.

**Comment by ngardiner** [comment]
Sounds good, @MikeBishop. Thanks!

**Pull request merged**
