### PR TITLE
Add support for Charging Amps & Available from total

### PR DESCRIPTION
**Pull request by VIDGuide**
Added chargerLoadAmps to the ajax data source
Added support for chargerLoadAmps in the JSRefresh code to populate the unused field
Added new <span> for "avail" amps, changed wording to "offered" (If this isn't the intent of the "avail" field, let me know and I can update accordingly)
Pulled Total data into var tot
Use total -> lastAmpsOffered for Offered Amps
Populate new chargerAvailAmps span with value

### CODE REVIEW

**Comment by VIDGuide** [comment]
image

**Comment by ngardiner** [comment]
Offered makes more sense than available in this context, I agree

**Comment by ngardiner** [comment]
I'm getting an exception:

```
Uncaught Error: Syntax error, unrecognized expression: #chargerLoadAmps:
```

Which I believe is from
```
$('#chargerLoadAmps').html(chargingAmps.toFixed(2));
```

But I can see the span:

```
<span id="chargerLoadAmps">0.0</span>
```

So I'm not entirely sure why.

**Comment by VIDGuide** [comment]
You're getting that in the browser console? Perhaps the HTML is cached from the page and not yet reflecting the new field? 

If the main.html.j2 edit is being reflected properly in the browser: Do you see the element in the page if you inspect the html?
image

**Comment by ngardiner** [comment]
I've worked out what the issue is:

The code here in jsrefresh is a bit redundant:

```
                   var chargingAmps = 0;
                    chargingAmps = parseFloat(json['chargerLoadAmps']);
                    $('#chargerLoadAmps').html(chargingAmps.toFixed(2));
```

Because the element is being set earlier by this code directly above:

```
                   Object.keys(json).forEach(function(key) {
                        [....]
                        $('#'+key+'a').html(json[key]);

```

And the reason that is failing is because in the JSON, you have a colon after the parameter name:


```
            "chargerLoadAmps:": ("%.2f" % self.convertWattsToAmps(chargerLoad),),
```

Which is what jquery is complaining about, I just couldn't see that the trailing colon in the debug output was because it was the key name, I was taking it as formatted output from jQuery:

image

What I'd recommend doing is:

   * Remove the following lines from jsrefresh, and if you need to manipulate the value at all, do it within the function above which automatically assigns the json keys to the element IDs with the same name

```
        var chargingAmps = 0;
        chargingAmps = parseFloat(json['chargerLoadAmps']);
        $('#chargerLoadAmps').html(chargingAmps.toFixed(2));
```

   * Remove the extra colon from the chargerLoadAmps JSON array element

And it should just all work automatically.

**Comment by VIDGuide** [comment]
You're absolutely right. I've got the other PR open which (stupidly, on my behalf) included the other changes as well, which I see is still open. (The one to add SoC to the current Vehicle panel) 
So I've added this fix to that PR as well. 
So this removes the extra ":", as well as the duplicated jQuery value and extract, as you note, this is actually able to be populated automatically via the jQuery since the ajax field and the jquery field are the same name. Neat. 

So if you're okay with the other PR for the SoC figures, then that PR includes this fix. 
If you'd prefer me push the fix on a separate PR, that's fine, just let me know.

**Comment by ngardiner** [comment]
Cool, sounds good! Let's fix it in the other PR, as I'd like to merge that too.

**Pull request merged**
