### PR TITLE
Added URL EMS Module

### PR DESCRIPTION
**Pull request by dehsgr**
This module is able to fetch generation and consumption data via a base URI concatenated with sub items for consumption and generation. It enables to receive such date e.g. from node-red provided http(s) endpoints.

### CODE REVIEW

**Comment by ChutneyMary** [comment]
Nice idea. Can I suggest that an example Node-Red flow be provided in the Docs. ie. a flow that can be pasted into the Node-Red Import Clipboard?

**Comment by dehsgr** [comment]
Yes, of course. I‘ll commit this ASAP.

**Comment by dehsgr** [comment]
Okay @ngardiner I just added documentation.

**Comment by ngardiner** [comment]
Awesome, thanks @dehsgr, this is a great contribution!

**Pull request merged**
