### PR TITLE
Feature /api/getUUID

### PR DESCRIPTION
**Pull request by jherby2k**
It is useful to have a unique identifier for a given TWCManager installation. Individual TWCs have a TWCID, but the master currently can not be distinguished from other TWCManager instances. Using IP addresses is problematic because they can change, and the Mac address (which this uses, under the hood) is not necessarily discoverable when the TWCManager is on a different network segment.

Use cases: Centralized logging, Home Assistant sensor unique identifiers.

### CODE REVIEW

**Comment by jherby2k** [comment]
@ngardiner I know you have limited time, but can you commit to including this PR in the next release? I'm asking because i've submitted my Home Assistant component (https://github.com/home-assistant/core/pull/53401) and they're asking me if it can be included in the upcoming release, August 4th. This month's focus is on power management, which is why they want it included i guess. The component depends on this getUUID method, so if you think that timeframe is not realistic let me know and i'll tell them it'll need to wait for September.

Thanks for your hard work on this!

**Comment by jherby2k** [comment]
@ngardiner I'm hoping this PR can make it into the next release, because my Home Assistant component depends on it for generating unique IDs.

https://github.com/home-assistant/core/pull/53401

**Comment by ngardiner** [comment]
Hi @jherby2k,

Yes, happy to include this in the next PR.

A question for you, though - I suspect this will work fine for a manual install, but for docker - do we know that it won't just generate a new UUID each time a container is spun up?

The hostname may not change but the IP probably will. I'm not sure of all of the elements included in the UUID calculation, but perhaps there's a better way:

   * Check the settings dict for an already generated UUID, if it exists, serve that
   * If not, generate a UUID using your routine and save it to settings["uuid"] so it persists even if there is a hw/os/etc change

It's also possible that the UUID calculation won't change, what I haven't had time to do is test it, so I am only speculating

Either way, I'll merge getUUID into 1.2.3, but we may need subsequent updates to it to make it stable for docker users if that turns out to be an issue.

**Comment by jherby2k** [comment]
It's based on the Mac address so it should be good, but I'll test a docker
install. Thanks!

**Comment by ngardiner** [comment]
Merging this, but I believe this will need a follow-up fix - MAC address isn't necessarily static for docker containers, it's based on the container ID, so if someone has more than one container per host, it could easily change.

**Comment by jherby2k** [comment]
Sure, I'm on a trip right now but I can do that in a week or two

**Pull request merged**
