### PR TITLE
Kostal EMS major update

### PR DESCRIPTION
**Pull request by hopfi2k**
Code refactoring, autodection of little/big endian encoding, detect inverter model and show in log, performance and stability improvements

### CODE REVIEW

**Comment by ngardiner** [comment]
Cool!

**Comment by ngardiner** [comment]
Just ran into an issue in my environment, it fails if you don't have a Kostal element in your config file:

```
        # try to read the config file
        try:
            self.configConfig = master.config["config"]
            self.configKostal = master.config["sources"]["Kostal"]
        except KeyError:
            self.configConfig = {}
```

Because it doesn't define ```self.configKostal``` if there's a ```KeyError``` thrown. Adding the following fixes it in my install:

```
        except KeyError:
            self.configConfig = {}
            self.configKostal = {}
```

**Comment by hopfi2k** [comment]
Sorry, my bad. Fix coming a minute

**Comment by hopfi2k** [comment]
Sorry, my bad. I accidentally committed an older version. Luckily my current version has the same fix as yours. Thanks very much!

**Pull request merged**
