### PR TITLE
Fix various Powerwall bugs

### PR DESCRIPTION
**Pull request by MikeBishop**
Everything is installed and running, but the code as checked in ran into some roadblocks.  These changes got me up and running.  I'm not confident the numbers are correct -- what's showing in the output doesn't exactly match what I'm seeing in the app -- but it's at least talking to the local API now.

### CODE REVIEW

**Comment by ngardiner** [comment]
Looks good @MikeBishop, thank you for the thorough review. I'm going to commit these and make a few slight follow up changes, that should help with out of the box Powerwall support.

**Comment by ngardiner** [comment]
Hi @MikeBishop,

I will be reverting one of the changes above (the direction of the operator for token check) committed in 49b1b6e to ask you to run a test for me if you could please. I'm looking to narrow down if there's an issue with API token caching for Powerwall2, as the logic is that the API token would be held in memory for 60 minutes after a login, reducing the interval for resending credentials. Your change would resend credentials each time which isn't a huge issue but it would be good to capture some output with this reversed so I could follow the flow and optimize the token handling.

The new messages will be logged at debug level 6 and will look like this:

Powerwall2 API token [API Token] still valid for [seconds] seconds.

Could I please get you to compare the API Token against the earlier logged message generated at debug level 4:

Powerwall2 API Login returned token [API Token]

And let me know if they match, and if the seconds remaining are logical (they should be 360 seconds minus the time since the last Powerwall2 login).

This change I have committed to v1.1.7 in b97eba0

**Comment by MikeBishop** [comment]
But using a token I think the situation is actually the reverse. `self.tokenTimeout > self.time.time()` is always true if the token is valid, and the action on true was to fetch a new token.  The Powerwall would attempt to get data, see that it needed to log in, get a token, then call the Start API because it had just gotten a token.  But Start would decide it needed a new token, get one, then call Start, and the cycle repeats endlessly.  49b1b6e switches the direction so you only fetch a new token if you're beyond the validity period.

(That is, under the old code, I never saw a message concluding that the token was "still valid.")

I do think there is an issue with the caching -- I was getting a 401 with an error something like "not enough parts" after I made the switch, but sending the request with no token at all worked fine (on my setup, at least).  That's why I made the change to not attempt the token at all if the password is unset.

**Comment by ngardiner** [comment]
You're absolutely right, my apologies @MikeBishop. I'll fix that up in the next commit.

**Pull request merged**
