### PR TITLE
WIP - modern UI for TWCManager

### PR DESCRIPTION
**Pull request by hopfi2k**
This is a WIP for a modern UI for TWCManager. Currently only supports viewing of data and no interactions.

### CODE REVIEW

**Comment by ngardiner** [comment]
Looking forward to taking a look @hopfi2k!

**Comment by mikey4321** [comment]
new GUI looks great! @hopfi2k

**Comment by ngardiner** [comment]
Seconded, great job @hopfi2k! I'm just hanging out for some decent sun/generation so I can see how it looks when it's charging.

**Comment by mikey4321** [comment]
Here you go.  

I noticed that there was only one decimal place on the amps number under charging, which isn't actually reading out the right value.  One decimal place is enough in my view.

Screen Shot 2021-02-05 at 2 48 06 pm

**Comment by hopfi2k** [comment]
Thanks guys for the positive feedback!

@mikey4321 The values under 'Charging' aren't updated yet, as I'm not sure which ones to display to make them useful...this relates to my question here #213 and certainly needs to be agreed on.

@ngardiner and @MikeBishop the continuous update of the values is something that this UI would really need to be useful, that in relation to #211 I really would love to get a more frequent update somehow...

@all please be advised that I haven't adopted full responsiveness yet. Right now, only the 'Home' part is correctly displayed (e.g. on a smartphone). The 'Charge Point' section is giving me headaches, because I'm not satisfied with the informations displayed. What should work (but can't test) is that multiple 'Charge Points' are displayed. If anyone with multiple chargers could try this, I'd appreciate.

Finally, from reading some of the Tesla firmware releases notes, it seems that - at least since mid last year - charging can be stopped by reducing the charging power to 0 amps. I haven't had a chance verifying this, but wouldn't his allow us to easily start/stop individual charge points? Even with a set charge duration (slider) and charge power (again with a slider)?

@ngardiner What I don't understand is that the cars VIN numbers isn't retrieved (and therefor not displayed). Shouldn't the VIN be fetched by TWCSlave.py?

**Comment by ngardiner** [comment]
> @ngardiner What I don't understand is that the cars VIN numbers isn't retrieved (and therefor not displayed). Shouldn't the VIN be fetched by TWCSlave.py? 

Only a subset of TWCs support fetching the vehicle VIN. If the TWC has the correct firmware it will do so, but because there hasn't been an online TWC firmware upgrade process for a long time (Tesla stopped it, presumably due to issues), devices with older firmwares won't have the functionality.

This is also true for other functions such as the ability to send start or stop charging messages to the TWC.

**Comment by hopfi2k** [comment]
Thanks @ngardiner for the explanation. Now things are much clearer (at least for me ;-) 

Is there another way to distinctly identify a connected vehicle (Tesla)?

Does anyone here has a TWC with a firmware that transmits the connected cars VIN? If so, is it correctly displayed in the UI?

**Comment by mikey4321** [comment]
> @mikey4321 The values under 'Charging' aren't updated yet, as I'm not sure which ones to display to make them useful...this relates to my question here #213 and certainly needs to be agreed on.

Realistically (I assume) most people only have one charger, plus you've got a very technical audience at this stage who know the practical limits.  I would keep it really simple and only show the actual Amps charging.  What the TWC is capable of, the VIN of the car etc would just clutter up your nice clean minimalist interface.  imho.

**Pull request merged**
