### PR TITLE
Fixing some odd bugs in old logic and improve using amps for 3 phases

### PR DESCRIPTION
**Pull request by dschuesae**
- Python tm_wday starts on monday, so scheduled charging did never work on the correct days. 
- Track Green Energy status was never returned because it was saved as -1 and then the value turned to 0
- Improved 3 phases amps for better charging

### CODE REVIEW

**Comment by MikeBishop** [comment]
IIRC, there was a comment in the code why the offset amperage were used, but I don't have it in front of me. I'm also unclear why nonScheduledAmpsMax would be negative, or why a negative value would be valid here.

**Comment by dschuesae** [comment]
// The last TWC in the list reported supporting under 40
                    // total amps. Assume this is a 32A EU TWC and offer
                    // appropriate values. **You can add or remove values, just
                    // make sure they are whole numbers between 5 and
                    // $twcModelMaxAmps.**
                    // Nietschy pointed out that his car was limited to 16A by
                    // onboard chargers, but setting the TWC to 16A leads to
                    // 15.7A actual usage.  When set to 17A, the car is able to
                    // draw a little more power, so we offer 17A instead of 16A
                    // below. 

But if your max is 16 it won't show you the 17 ;-) This problem I will work on later.

**Comment by dschuesae** [comment]
> Re commit [810d588](https://github.com/ngardiner/TWCManager/commit/810d588776042cac9ca6eac2427e81a8ffd15731):
> 
> `nonScheduledAmpsMax` is the fall-back when no other charging option is available. If `nonScheduledAmpsMax = 0`, it means that the vehicle should not charge if there's no scheduled charge, green energy, chargenow or other higher priority policy rule active.
> 
> `nonScheduledAmpsMax` value gets sent as an absolute value of `charge_amps` by the Policy module if the non-scheduled charging policy is active, and that then gets passed to `setMaxAmpsToDivideAmongSlaves`, which sets `master.maxAmpsToDivideAmongSlaves`, which is read by `getMaxAmpsToDivideAmongSlaves`. `getMaxAmpsToDivideAmongSlaves` checks if it is below < 0 and if so, sets it to 0.
> 
> So ultimately, setting this to `-1` only results in a value of `0` anyway, I can't see any code path that honours `-1` as a valid value for `nonScheduledAmpsMax`. The old web gui (the PHP based UI) used -1 as a default setting for a number of settings, I suspect that is where this value comes from, but the old webui is in the process of being deprecated and it's likely not worth the effort of changing it.

You're right. In my changes to your 1.8.0 branch I even changed the policy. But it is not compatible anymore with old ui. That does not really matter if somewhen we can set everything in the new ui.

For me the most important change is tm_wday - because it's just not working as it should and I use it. As you manually merged this one. I will close this one.

**Comment by ngardiner** [comment]
I'll open an issue to deal with this, as I'd like to make it available again with a change to the policy.

**Comment by dschuesae** [comment]
Have a look here https://github.com/dschuesae/TWCManager/commit/df8ffa8d41cc616fd2604cd90ea007e033ddd432

I already did this for 1.8.0. It was working fine.

**Pull request closed without merging**
