### PR TITLE
Limit by mode

### LINKED ISSUE #14: Feature request: Charge limit per mode
Since you can set the charge limit via the Tesla API, would be nice to have the desired charge as a parameter for each charge mode (e.g. only charge to 50% during scheduled charging, but to 90% when on green power).

### PR DESCRIPTION
**Pull request by MikeBishop**
Fixes #14.

This is a lot of code and not yet tested on a live system, hence the draft status, but reviews appreciated for anything I've obviously broken.  I have all the hardware now; I just need a free evening to open up the TWC and install the Pi before I can test.

I already found one bug in tonight's code, but it's late and I'm not fixing it before bed:  I use `settings.` to retrieve the desired values, but `config.json` doesn't populate settings but its own thing.  That probably needs an update to `policyValue()` to enable it to retrieve items off of config.

### CODE REVIEW

**Comment by MikeBishop** [comment]
Rebased on top of #37 and tested on my system.  I haven't tested the arrival/departure paths yet (I've been at home the whole time), but I think this is at least ready to be tried by others.

**Comment by MikeBishop** [comment]
Found and fixed issue with departure code; I think arrival and departure are now functional.  Have at it!

**Comment by ngardiner** [comment]
Very comprehensive, thanks @MikeBishop. To make this process easier, I'll make a release tomorrow for the current v1.1.7 version, add a development branch for v1.1.8 and get merging your improvements, so we can test / adjust as needed. Appreciate your patience and working with me on the last few PRs, I have been on vacation and in transit for the last week so it has been a bit hit and miss with the merging and a few reversions, but I believe we're making good progress in getting your logic merged.

**Comment by MikeBishop** [comment]
I think there's still something odd that happens overnight -- this branch seems to work properly the day I launch it (while in the green energy policy), but breaks in various ways as it cycles through the other policies and limits.  I feel like I find a fresh typo each morning.  🤦‍♂️  Still, this is what I'm running on my system, so we'll eventually shake out the bugs.

**Comment by ngardiner** [comment]
Hi @MikeBishop,

I've done a merge of the changes in your fork to v1.1.8. It isn't reflected here because I cherry-picked the commits one by one as we had a few conflicting commits in the interim, but it is a complete merge currently.

I'll run some limited testing against the new code in parallel. The documentation still advises checking out v1.1.7 so none of the changes should impact others which gives an ideal opportunity to test in advance of v1.1.8 becoming the recommended release.

Would be good to get your feedback as to whether v1.1.8 is working in place of your current v1.1.7 fork. One significant benefit of v1.1.8 is a much better install process which I'm about to update in the issue tracking this requirement.

**Comment by MikeBishop** [comment]
I've been merging in v1.1.7, so I'd have expected a merge (rather than a rebase) to have succeeded or had some trivial conflicts.  Regardless, I'll switch my Pi to v1.1.8 and see what we find.  Things I still want to track down before we ship this:

- I'm seeing the car woken periodically during scheduled charging.  In theory, once it's received both the new limit and the command to charge if it can, it should be permitted to sleep.  I'm not sure what code path is leading to the wake-up.
- The limit doesn't appear to get applied during scheduled charging, and I can't figure out what's going wrong there.  My car charged to 90% both of the last two nights, despite the limit being set for 50%.
- I worry that the new amperage gets offered by the TWC before the car has a chance to learn the new limit.  I'm considering adding some logic that if the selected policy has changed, apply the new limit immediately but don't apply amperage changes until the next run.  Keeping track of when policy selection changes could also help with #40.

**Comment by ngardiner** [comment]
A merge would have succeeded, but given the rebase skipped 3 or 4 commits that we had already merged out of order via other PRs in the interim, it not only saved time, it also helped address the other 4 or so conflicts individually. So certainly in terms of expediting the inclusion of the PR it was worthwhile.

For point 1 above, by sleep do you mean that we cease to poll/communicate with the Vehicle? I don't believe that the vehicle ever enters the sleep mode as we know it whilst charging.

For the third point, would the gap between setting amperage and setting the new limit be significant? Whilst it might charge the vehicle momentarily where a policy would not have the vehicle charging at all, it wouldn't be a considerable amount of additional charge I wouldn't think. That said, your solution sounds like a sound one.

**Comment by MikeBishop** [comment]
> For point 1 above, by sleep do you mean that we cease to poll/communicate with the Vehicle? I don't believe that the vehicle ever enters the sleep mode as we know it whilst charging.

I mean that once the car has reached its targeted charge, it shouldn't be polled and can go to sleep (until the next time the limit changes, anyway).

> For the third point, would the gap between setting amperage under the new matched policy and setting the new limit be significant? Whilst it might charge the vehicle momentarily where a policy would not have the vehicle charging at all, it wouldn't be a considerable amount of additional charge I wouldn't think. That said, your solution sounds like a sound one.

It's probably not huge -- a few seconds at most, assuming that background tasks execute promptly.  But part of the logic to not doing stop_charging within a minute of electricity flowing is that we don't want to overuse the relay in the TWC.  If the car is above the new charge limit, I'd like the TWC to offer the higher current, and the car to decline, so the relay never engages.

**Comment by MikeBishop** [comment]
Actually, it's not even *that* simple -- because if you update the charge limit first, the reverse happens at the end of a period.  You tell the car that it should change its limit from 50% to 95%, so it starts charging a few seconds before the code drops the allowed amperage to zero and tells it to stop.

Ideally, you'd decrease limits before offering more amps, but reduce amps before increasing limits.  Factoring in that, hypothetically, the limit for the new policy could be -1, which in turn means that each vehicle could have a different limit being applied, and it's indeterminate what direction that is from the current limit.

This relay toggle may just be unavoidable without more logic than it's worth for right now.

**Pull request closed without merging**
