### PR TITLE
if control or status modules not installed, continue without them

### PR DESCRIPTION
**Pull request by AndySchroder**
Part 1 of resolving https://github.com/ngardiner/TWCManager/issues/90

### CODE REVIEW

**Comment by AndySchroder** [comment]
I understand the first part of your comment, but the final part, I don't understand.

Remove

    if 'WebIPCControl' in locals():
        webipccontrol.processIPC()

and replace it with 

    master.getModuleByName("WebIPCControl").processIPC()

or, 

    if 'WebIPCControl' in locals():
        master.getModuleByName("WebIPCControl").processIPC()

? I am not sure which you mean.

**Comment by AndySchroder** [comment]
I have added another pull request, https://github.com/ngardiner/TWCManager/pull/96/commits/1951b8bd9d83732abce456e0205c7f7bcb83b988 . This addresses Part 2 of https://github.com/ngardiner/TWCManager/issues/90 .

Please note, if you do a diff where you ignore leading white space, there are not many lines that actually change in this pull request. If you have meld setup as your difftool, this is easy to do under preferences.

**Comment by ngardiner** [comment]
> if 'WebIPCControl' in locals():
>     master.getModuleByName("WebIPCControl").processIPC()

This would be ideal, thanks.

**Comment by AndySchroder** [comment]
Done. Please let me know if this works. I don't have WebIPCControl setup to test myself.

**Comment by ngardiner** [comment]
Will do, thanks for that @AndySchroder

**Comment by ngardiner** [comment]
Great, part 1 is merged @AndySchroder and I have tested it successfully in a few different test cases. I did end up trapping another exception (ImportError) for python versions prior to 3.6 as they don't define the more specific ModuleNotFoundError.

I will need to attack part 2 when I have a little bit more time to merge and test it.

**Comment by AndySchroder** [comment]
Just curious, what type of merging process did you use? Still learning how merging works. Looks like you have no reference maintained to my branch, but you still listed me as the author of the commit. Not totally sure how that works.

**Comment by ngardiner** [comment]
Apologies for the late reply. I used the mailbox method (I used your patch and applied it in chunks using ```git am```) - this was so I could split the first and second phases of the patch. I'm definitely happy to merge the second half of your solution, but I also wanted to do it when I had time to run some tests afterwards and do my best to check it before merging it into the dev branch which has quite a few active users.

**Comment by AndySchroder** [comment]
Hello,

You closed this pull request, but didn't accept all of my commits. At this point your branch is so far ahead such that I'll have to re-do the changes manually and then re-commit. Before I waste time trying to do that, what is the likelyhood you'll accept new commits from me? Was there something you didn't agree with in my previous commits? I have a new product (http://andyschroder.com/DistributedCharge/BoardA0/Overview/) designed to work with TWCManager and I have yet another small change required to make it work with my RS-485 interface. It would be great if my product could be supported in the latest version/branch of TWCManager that you are working on.

Thanks.

**Pull request closed without merging**
