### PR TITLE
add config option to set home radius for cars

### PR DESCRIPTION
**Pull request by dtiefnig**
Historically, cars were considered at home when latitude and longitude were within about 10560 feet of the discovered home location. The four miles square area is quite big, and in many cases will be too big. As it is pointless setting a different arbitrary limit for all users, let them choose themselves.

### CODE REVIEW

**Comment by ngardiner** [comment]
Hi @dtiefnig,

Thanks for this. I think an override for the home location radius makes sense.

My main feedback would be that I think the setting should be commented out by default in the config. It's really daunting for new users of TWCManager to work out what they do or don't need to configure to make it work and I'm big on not contributing to this by making it clear when something is totally optional. Not many people would be at the point where they feel that playing with the atHome radius is necessary. 

Also just some quick feedback on the code, there's a nice way to do what you're doing when reading the config parameter:

```
        try:
            atHomeRadius = 1/364488.888 * self.config["config"]["atHomeRadius"]
        except KeyError:
            atHomeRadius = 1/364488.888 * 10560
```

In a single line:

```
atHomeRadius = 1/364488.888 * self.config["config"].get('atHomeRadius", 10560)
```

**Comment by ngardiner** [comment]
I'd also add to that slightly by wrapping the config value in an int() or float() in case the config is cast to string or has a minor issue like a trailing space - it won't fix all incarnations of potential config error such as someone setting atHomeRadius to "banana" but it could help with someone quoting the number for example:

```
atHomeRadius = 1/364488.888 * float(self.config["config"].get('atHomeRadius", 10560))
```

**Comment by dtiefnig** [comment]
Ah, sure using get() is much better in any case than accessing class variables from the outside.

Also commented the config option so it is not part of the default config. I guess we do not have to adapt `tests/API/test_getConfig.py` then, right?

How about the other config files in `etc/twcmanager/`? Not sure what they are exactly used for, but I've added the option to `demo.json` and `.testconfig.json` as well. As it is commented anyway, it should not be able to break anything.

**Comment by ngardiner** [comment]
Looks great, thanks @dtiefnig (and apologies for the recent delays)

Those files are used by the CI test suite to run up TWCManager and perform automated tests. As you say, it doesn't matter for those as the feature is turned off, but it's really nice that you're keeping them in sync because in the future it might become part of the testing

**Pull request merged**
