### PR TITLE
Exponential error backoff

### LINKED ISSUE #219: API backoff in background thread
The Tesla API seems to be particularly laggy today, which is causing an interesting occurrence on my system.  Since the API sleeps for one minute when it encounters a known issue like a timeout, and it makes up to three attempts within one background task execution, it blocks all other background tasks from running during that time.  Including the background task that checks production / consumption numbers.

Now, if you only have one car, this is purely a cosmetic issue most of the time -- if the car isn't responding, it's probably not charging either, so you can afford to wait to adjust what the TWC offers.  But if you have multiple cars and one car is unresponsive while the other is charging, this seems like it could end badly.

I see two possible paths forward:
- Remove the 60-second sleeps and unify the error code paths to try again later.  Instead of a fixed "1 minute for some errors, 10 minutes for others," switch to increasingly long backoffs for all repeated errors.  1 minute, then 3, then 5, then 10, etc.
- Move the generation/consumption polling to its own thread, separate from the background task loop.

I'm more inclined toward the first, but they seem like similar amounts of work.

### PR DESCRIPTION
**Pull request by MikeBishop**
Fixes #219.

Removes the concept of transient errors, which cause a 1 minute delay in the background thread, blocking all other background tasks.  Instead, all errors (other than "could_not_wake_buses") lead to failure of the current task and an exponential backoff (which starts with a smaller delay than it previously did).  This has been running on my system for a week and a half now, and it seems to work okay, but obviously I can't verify all the corner cases.

### CODE REVIEW

**Comment by MikeBishop** [comment]
@hopfi2k, this had a bunch of conflicts with your changes in #226.  I *think* I resolved them all properly, but I'd appreciate it if you'd review it for anything I accidentally reverted or stomped on.

**Comment by hopfi2k** [comment]
@MikeBishop your changes are looking good to me, but will test and report back if I stumble over something

**Comment by ngardiner** [comment]
Sorry @MikeBishop, I broke your PR with the shift from v1.2.1 branch to ```main```. Any chance I could get you to create a new PR retargeting the merge to ```main``` and I'll get it added straight away to v1.2.2 as I think it's a great addition

**Comment by MikeBishop** [comment]
The main thing I've noticed with this is that my car seems to take longer to wake up.  I'll try to resolve the conflicts soon.

**Comment by MikeBishop** [comment]
I think this is appropriately retargeted now, but probably worth re-testing.

**Comment by ngardiner** [comment]
Thanks for the effort to retarget @MikeBishop, much appreciated

**Comment by MikeBishop** [comment]
Going ahead and merging -- this seems fairly reliable lately, and I'd like it to get some broader testing.

**Pull request merged**
