### PR TITLE
UI tune up & Responsive Fixes

### PR DESCRIPTION
**Pull request by VIDGuide**
- Adjust some minor sizing elements
- Fix the Charging Policy buttons to stack in responsive/mobile sizes
- Added Server date/time to navbar to aid UTC/Local Time/Sync tracking
- Corrected SoC hiding logic when no car connected or history

image
image
image

### CODE REVIEW

**Comment by VIDGuide** [comment]
- Dropped seconds from the server time so it doesn't look so "unsmooth"
 image
- Added a null check for vehicles so the vehicles page can load without throwing an exception/blank page if none are defined/registered.
- Improved grid layout for Charge Now controls for mobile/responsive layout. Sliders were very tiny on phone sized screens and very difficult to adjust by touch. Adjusted to stack.
image

**Comment by ngardiner** [comment]
This is looking much better on mobile @VIDGuide, thank you! A couple of pieces of feedback from me:

   * I think we should make the server time display configurable in settings. It's nice to have, but it also uses up a fair bit of room - I'd be inclined to set it off by default, but others may prefer differently, and I'd go with the majority opinion on this

   * I've found that the charge timer output gives an output to 6 decimal places for seconds, Rounding that to 2 digits would be great:

image for 

Everything is looking really good with the changes you've made, thank you again for your contributions.

**Comment by VIDGuide** [comment]
Great points. Pushing a patch to drop microseconds completely, HH:MM:SS is plenty without the microseconds.
I'll see about making the server time an option, that makes sense. I only really used it for 2 things, 1 to confirm I had the timezone setup properly, and for checking the heartbeat from client <-> server is still updating/refreshing.

**Comment by VIDGuide** [comment]
Add settings UI for enabling/disabling server time in UI:
image

**Comment by VIDGuide** [comment]
Added the extra Cancel Charge Now button for Charge Now - fixes #277

**Comment by ngardiner** [comment]
Looking good! Let me know when you're ready for me to merge the changes and I'll hit the button.

**Comment by VIDGuide** [comment]
Yeah I think you can hit it now. I will be looking into adding a "charge time left" timer/display at some point, and maybe see what other commands we can enable on the UI, but i'll make a new PR for that.

**Pull request merged**
