### PR TITLE
Calculation from amps to watts does not work for 3 phases with 240V

### PR DESCRIPTION
**Pull request by dschuesae**
So I changed it to my observations and it works like a charm. It will work for 1 phases. But there is a big question about 400V 3 phases systems. How to they differ from the other two?

### CODE REVIEW

**Comment by MikeBishop** [comment]
I don't have a three-phase setup, so I'm delighted someone who does can go find my bugs. But wasn't the power conversion for three-phase a sqrt(3) multiple? Or am I missing something basic? I freely admit I haven't used those calculations for almost two decades now....

**Comment by dschuesae** [comment]
Yes, but for the all 3 phases, and not for every phase. And we get the data for every phase.

**Comment by dschuesae** [comment]
I just checked again. I have an 400V installation but every phase is returning 240V.

**Comment by ngardiner** [comment]
In a 400V 3-phase system, there is 400V between any two phases, and ~240v between each phase and neutral.

**Comment by MikeBishop** [comment]
I had theorized, based on the wiring diagram, that the TWC would see 240V three-phase as two voltage readings instead of three, since the third phase is wired to the neutral terminal instead of L3. But of course, I can't confirm that from my single-phase system.

**Pull request merged**
