### PR TITLE
added growat EMS

### PR DESCRIPTION
**Pull request by the-dbp**
added growat EMS

### CODE REVIEW

**Comment by ngardiner** [comment]
Great stuff, thanks for the new interface! Those values (for the battery SOC and generation) should go into the config file - if you'd like I can just merge your changes and update it to read those from config, but you would then need to add that to your config file afterwards or my changes would break your setup.

Essentially, the changes would look like:

```
self.useBatteryAt = self.configGrowatt.get("useBatteryAt", "")
self.batteryGenerates = self.configGrowatt.get("batteryGenerates", "")
```

Although I think we could sync the terminology with our other battery module. ```useBatteryAt``` is called ```minBatteryLevel``` in the Powerwall EMS module and ```batteryGenerates``` would maybe be better as ```maxOutput```?

**Comment by the-dbp** [comment]
I'll happily implement the changes, and I also want to implement one other thing because right now it charges like this:
image

which I don't love so I think I'll add a "discharge till" in the config and ems as a value it will discharge down to once useBatteryAt has been reached, with that implemented I think "minBatteryLevel" can lead to some confusion

so i'll do the following:

- add useBatteryAt and maxOutput to config.json
- load values from json into ems
- impement dischargeTill

**Comment by the-dbp** [comment]
I have added a timing function as well so it doesn't discharge the battery after a configured time, if i discharge my ups early in the day it'll likely reach to recharge but in the evening it will just discharge and then the battery capacity wont be enough to get through the night.

I have tested this implementation over a couple of days and it seems to work well. (for me anyway)

**Comment by the-dbp** [comment]
there's and issue with how often this app wants to update, the substraction of the charging power and how low frequent the growatt api is, causing some spikes. can you set the update frequency anywhere in the config?

**Comment by MikeBishop** [comment]
In your config file, look for `policyCheckInterval`, which defaults to 30 seconds.

**Comment by ngardiner** [comment]
Thanks @the-dbp. Because we changed the structure of the development tree between v1.2.1 and v1.2.2, I had to retarget your changes - took me too long but that is now done and I'm merging your Growatt module now. Thank you very much for your awesome contribution!

**Pull request closed without merging**
