### PR TITLE
New menu Graphs, it allows to represent energy graphs base on the SQL…

### PR DESCRIPTION
**Pull request by juanjoqg**
… database

### CODE REVIEW

**Comment by ngardiner** [comment]
I really like it @juanjoqg! It's a really cool feature and a great use of the data we collect. Thank you.

It does need some additional work, primarily because it does rely on some static assumptions about how TWCManager is configured, and that would work in an environment where MySQL is in use, but I'd like to see it use a standardised approach to querying data via Logging modules.

I'd like us to expand on the work that you've done, to modularise the functionality and make it work across multiple different modules. It wouldn't require too many changes, but it would require a bit of a change of approach for some parts of the code.

How would you prefer we deal with it?

   * If you would like, I can provide some feedback in a review of the PR to guide some of those changes, so we deal with the logging modules a bit more dynamically, and we automatically detect if an appropriate logging module is in use and if so, only then display the option to view the Graphs (and query the logging module via a common API)

   * If you're happy with the code as is and you're not too worried about refactoring the code to do the above, I am happy to merge your changes, and then I can follow up with the changes needed to modularise it.

**Comment by MikeBishop** [comment]
I'll just mention the overlap with https://github.com/MikeBishop/MMM-Powerwall and invite you to steal any code or design you feel is relevant.  ;-)

**Comment by juanjoqg** [comment]
@ngardiner , let me know how you think it should be integrated. Right now I'm working in a new pricing module, but I'll give it a try when I can.

@MikeBishop your graphics look really cool, mine are much simpler, thanks for sharing.

**Comment by ngardiner** [comment]
Sorry, I've been extremely time poor lately which means I haven't had a chance to update this, let's merge it as is and I'll do some quick refactoring afterwards.

**Pull request merged**
