### PR TITLE
Show SoC state in Modern UI

### PR DESCRIPTION
**Pull request by VIDGuide**
Added ability to render current (last polled) State of Charge and the cars target SoC

I understand this is affected by the frequency of polling the Tesla API (default 30 minutes), so is a little bit lagged behind, but if the polling frequency is increased, this becomes more accurate. 

Also set bold on the Vehicle overall heading, to make it stand out a little clearer from the Current/Last sub-headings

image

### CODE REVIEW

**Comment by ngardiner** [comment]
Loving the UI updates, thanks @VIDGuide!

**Comment by VIDGuide** [comment]
Is there a known rate that's "safe" with the Tesla API? 30 minutes is a bit long for SoC data to be particularly accurate. I see that things like TeslaMate and the Nikola mobile app seem to poll it much faster. I've updated my config file to do it once per minute and so far it hasn't thrown an error. Do you know if there is a rate limit on the API we should be aware of?

**Comment by VIDGuide** [comment]
Okay, sorry, that was a lot of commits to basically pare it back to a minimal setup.
image

I moved SoC to a new line, makes it suit better since it doesn't "belong" to either current or last vehicle, it's just 'last SOC'

**Comment by ngardiner** [comment]
> Is there a known rate that's "safe" with the Tesla API? 30 minutes is a bit long for SoC data to be particularly accurate.

Off the top of my head I couldn't say if it was any more than arbitrary, but we do constantly toe a line of attempting not to keep a vehicle awake if it is not charging, so there's certainly potential for issues if we increase polling intervals. We'd need to carefully assess potential impact of decreasing the polling interval - and at that point I guess the question becomes: how often do we need it to update to be accurate as a UI element.

**Comment by VIDGuide** [comment]
> > Is there a known rate that's "safe" with the Tesla API? 30 minutes is a bit long for SoC data to be particularly accurate.
> 
> Off the top of my head I couldn't say if it was any more than arbitrary, but we do constantly toe a line of attempting not to keep a vehicle awake if it is not charging, so there's certainly potential for issues if we increase polling intervals. We'd need to carefully assess potential impact of decreasing the polling interval - and at that point I guess the question becomes: how often do we need it to update to be accurate as a UI element.

I've been monitoring that with TeslaMate:
image

The yellow is charing, aqua is online, green is sleeping. I have mine set to poll every 1 minute since a few hours ago, doesn't seem to have stopped it going to sleep after it was done charging. (The yellow was a 1 hour "Charge Now" that expired, shows it was online for a few minutes, then went to sleep. 

So if nothing else, it looks like polling this API doesn't wake the car specifically.

**Comment by ngardiner** [comment]
The problem is it's different for different vehicles, hence why there's so many sleep settings in TeslaMate for example. Changes like this need a lot of testing, so my recommendation would be to handle the UI first and give any changes like this a lot of time to be tested widely.

**Comment by VIDGuide** [comment]
And that’s why you’re the expert :)

cool, well, this PR is 100% UI only, it’ll show the SoC to whatever value/delay the system is running, leave it up to the user to tune that as they see fit :)

**Comment by MikeBishop** [comment]
TeslaMate gets this from the websocket API, which we don't support.  (And don't really need to, plus you can only have one WS client active at a time, which is Teslamate for many of us.)  If we expanded our MQTT support to listen to Teslamate's updates, we'd get live status from there.  Definitely an option, attractive to get real-time GPS and charge data without polling, but not really necessary to the core functionality.

For policies that depend on charge state to enter/exit, we expose a background task that polls the charge more frequently.  However, you only get one background task per policy, so you can't use that workaround for Track Green Energy.

**Comment by VIDGuide** [comment]
Good points, and fair enough. Either way, all good, this is just a UI to the values that the back-end knows about. If those remain at 30 minute update intervals, that's fine, if it's more frequent at the users adjustment, or if those background tasks update these values too when in operation, then the updated values will reflect here.

**Comment by ngardiner** [comment]
> f we expanded our MQTT support to listen to Teslamate's updates, we'd get live status from there. Definitely an option, attractive to get real-time GPS and charge data without polling, but not really necessary to the core functionality.

Agreed, I think there's two things about our architecture that make this a particularly good idea:

- Many of TWCManager's users will also use TeslaMate, and if not, they may use another similar system which does datalogging. This is important because reading a value at high frequency for a datalogger is core functionality, as it writes this data to a database in an optimized format and therefore provides a service - whereas consuming it at high frequency for TWCManager simply updates a UI element that someone may not even be looking at. We risk contributing to load on Tesla's API and getting 3rd party software banned and we end up consuming the same data we're already consuming elsewhere - duplication of effort.

 - We have a modular architecture, by design we like talking to other systems. If we offer modules to talk to dataloggers (where they support it) to increase the user feedback, we reduce the network connectivity and load on Tesla's servers by half, but both systems benefit. Also, the authors of that software tend to do a stellar job of handling API comms because it's the bread and butter of those systems, whereas for us it's a necessary evil that we'd probably rather avoid

The importance of separating the UI from the logic is that we can monitor the data that we have today, and then add functionality on top to improve the update rate without breaking what's working today. Not only would subscribing to TeslaMate's MQTT messages be exceptionally easy to do, it would likely give us other values that we need to work with as @MikeBishop mentioned such as GPS, so we could start skipping our internal API calls if a working datalogger is attached,

**Pull request merged**
