### PR TITLE
History

### LINKED ISSUE #100: API Wish:  Charging history
I'm building something separate that will display a graph much like what the Powerwall app displays -- where energy came from, where it went -- but I'd like to support pointing to a TWCManager instance and showing car charging as a separate line on the graph from house consumption.  In order to do that, I'd need to be able to grab the charge current over the last ~24 hours of history.  (I think the Tesla API reports history with averages over 5 minute intervals, so I'd probably do the same here.)

I'll likely build this myself, but if you have suggestions about where to hook in, feel free to suggest!

### PR DESCRIPTION
**Pull request by MikeBishop**
Had a chance to look at this over the weekend.  Fixes #100, plus some extraneous Black impacts.

This solution does increase writes of settings.json, but I think that's unavoidable if we want any persistence of data.  It minimizes the writes by:

- Only storing non-zero values; missing values are interpolated as zero by the response code
- Sampling every five minutes (for alignment with the Tesla API)

So at most, it's one write every five minutes while charging, and an idle system doesn't do any extra writes.

### CODE REVIEW

**Comment by ngardiner** [comment]
Great stuff, thanks @MikeBishop.

I am not really convinced one way or another if we are concerned about flash write fatigue having this turned on by default. On the one hand, this is probably less writing than the syslog logging that normally occurs on an rpi, on the other hand not everyone will be polling this data.

As a compromise instead of adding yet another config block to the config file, I was thinking of having an enabled by default checkbox in the web interface which itself is stored in settings.json, which could be unchecked via the web interface for those who expressly want to turn off the writes - what are your thoughts?

I'd go ahead and do the same for VIN and charge recording if this was considered worthwhile.

**Comment by ngardiner** [comment]
Also, just a pickup during testing, the following breaks python versions < 3.6:

```
  File "/usr/src/TWCManager-v1.2.0/lib/TWCManager/TWCMaster.py", line 90, in advanceHistorySnap
    futureSnap = datetime.now().astimezone() + timedelta(minutes=5)
ValueError: astimezone() cannot be applied to a naive datetime
```

I'll trap the exception, and might have to update the docs to recommend a newer python version going forward. Currently it will break for those of us still on raspbian stretch, running python 3.5.3.

**Comment by MikeBishop** [comment]
Sorry, I missed that version restriction.  I tried a couple different ways to get a timezone-aware DateTime in the system timezone, and that's what I eventually found to work.  If there's a more backwards-compatible way, I'd be happy to switch to it.

**Comment by ngardiner** [comment]
The < 3.6 alternatives look a bit messy, to be honest. I think we'll have to bite the bullet at some time and draw a line under a minimum 3.x python version as there will just be a larger delta in future.

If we are happy with a stopgap measure for now, I'll do some research on if there's a backport of a newer python package for us older dist users, and if so I'll update the doco to recommend it. It is useful having an older target (in my installation) though as it means we can catch some issues that might crop up for a handful of others who are on earlier python 3 versions.

If I only had free time to spend, I'd go ahead and spin up a few different environments and a CI pipeline to test the code across those. The problem is there's more work than it sounds involved - at the moment there's serial communications as a dependency, I was meant to work around that with the dummy interface modules so it could be run up in a simulated mode, but they are hardly high on the priority list, and there's a lot of work still to do to get to that point.

**Pull request merged**
