### PR TITLE
Alternative maximum

### PR DESCRIPTION
**Pull request by MikeBishop**
I don't know if it's a result of measurement error or car calibration, but my TWC almost always reports the car pulling more current than the limit set.  When the limit is small, it's a fraction of an amp, but when the limit is high, it's 1-2A extra.  Yet when the car is being offered (hypothetical numbers) 36A and decides to pull 38A, the current code can decide to offer 37A thinking it's reducing the load.

This change adds a sanity check by comparing to what was previously being offered:
- If generation > consumption, the TWC can't increase its offer more than the difference
- If generation < consumption, the TWC must reduce its offer by at least the difference

This should help track solar output more closely, despite the car's... overeager ways.

### CODE REVIEW

**Comment by MikeBishop** [comment]
Just happened to catch this in action....
image
Consumption is exceeding generation, but based on the usual math, TWCManager thinks continuing to offer 25A will correct the issue.  Instead, this logic kicks in and makes it reduce to 24A, bringing consumption back in line with generation.

Now, the down side is that presenting it as an equation is no longer true, so the math looks funny.  😒

**Comment by ngardiner** [comment]
This is great, @MikeBishop. Perhaps what we can do is just fudge the equation to always be true. For example, we could add the difference between (generation - consumption) - total to consumption to ensure it balances as a "round" output value. What does worry me though is it could hide issues down the line. Perhaps a development switch to keep it to reported values for those who anticipate the gap. What do you think?

**Comment by MikeBishop** [comment]
The way it's implemented currently, there are two values that may be wildly different, and you take the lesser of them.  If you're not charging, the "alternative maximum" is going to be huge -- you're currently offering 25A, you've got 25A spare capacity, so you must not offer more than 50A -- and the math shown will be correct.  It's only if you are charging that this limit comes down to potentially less than what it would calculate.

I think what you're suggesting is that instead of showing the second number as the actual consumption offset, we retcon it and show the difference between generation and what we've decided to offer.  It's a little less obvious that this number will not always be ( consumption - charger ) / 240.  That should be easy enough, and add a level 10-11 debug output to say that we've tweaked it.

**Comment by ngardiner** [comment]
> I think what you're suggesting is that instead of showing the second number as the actual consumption offset, we retcon it and show the difference between generation and what we've decided to offer.

Moreso that we balance the figures on output as a "friendly" output approach. ie we increase consumption by the difference between consumption - generation and total, The point of this exercise would be that regardless of small tweaks to improve efficiency, the "nice" output value would always balance. As you have rightly pointed out, we could then offset that with a precise output value at a higher debug level which shows a more specific/precise breakdown, so as not to over-complicate the equation.

**Comment by MikeBishop** [comment]
Note that I can't actually try this until I'm in green energy and charging (and I don't want to try tricking my system into thinking it's sunny tonight).  Sunday is the next semi-sunny day in the forecast, so I'll verify the logging change then.

**Comment by MikeBishop** [comment]
We got some sun this afternoon, so I stepped through the new logging code, and it seems to work:
image
Someone looking closely might notice that (8675 - 7908) / 240 = 3.20 instead of 4.12A, but it's not as blatantly wrong now.

**Comment by ngardiner** [comment]
Fantastic, looks great. I think as long as we have the equation balancing, it's unlikely to look like a bug on the user-side, even though it is infact an optimization.

**Pull request merged**
