### PR TITLE
Add Tesla MFA Support for Login Flow

### PR DESCRIPTION
**Pull request by ngardiner**
(Finally) adding MFA support for Tesla login. 

**Progress**
- [x] Unify current login flow as Default and Modern themes implement differently
- [x] Add form for submitting MFA code for MFA login
- [x] Send MFA token code to Tesla API during login flow
- [x] Reflect MFA token authentication success/failure in the UI

**Testing**
- [x] End to end login flow under Default theme - MFA
- [x] End to end login flow under Modern theme - MFA
- [x] End to end login flow - Non MFA

**Things to follow up**
   * I think that due to the nature of form parsing in HTTPControl module, we may truncate leading zeros in MFAs meaning an MFA starting with a zero may fail - **confirmed**
   * Easy fix to consider for the above - zero pad any number submitted to 6 digits **fixed**

### CODE REVIEW

**Comment by ngardiner** [comment]
Thanks, I can see the issue, seems to be related to the merge of #219. I'm investigating.

**Comment by ngardiner** [comment]
Found the issue, fix is incoming

**Comment by ngardiner** [comment]
Thanks all for the reports, found the issue. If you do a ```git pull`` from ```main``` branch, it should be working again.

**Comment by alexeiw123** [comment]
Have updated - I'm getting this error now: Failed to log in to Tesla Account. Please check username and psssword and try again.
(psssword is as copied)

URL is http://192.168.1.65:8080/teslaAccount/False

This could be unique to me and related to my use of the '+' character in my tesla account email address, as I give account access to this unique address from my main account, so that I can revoke access should I ever need to.

**Comment by ngardiner** [comment]
It may be the plus, as plus is used in URL encoding for spaces, but I'd need to test that further - but it wouldn't be anything to do with the MFA support specifically as the MFA branching happens after the login with password when Tesla then challenges us for token code, so if it that is the case it would have affected anyone with a + in their email ever (MFA or no MFA, prior to the Tesla auth changes). Can you log in to the Tesla website with that account? Tesla often lock accounts if several failed login attempts occur, I've had to reset mine a number of times.

I can confirm that I can log in to both MFA and non-MFA accounts however neither have a plus in them, I'll need to create a new account (later) to test this specifically. Appreciate the heads up, I'll know whether it is reproducible this evening after some testing.

**Comment by ngardiner** [comment]
Just to confirm I haven't forgotten the 2nd part of your message either @mikey4321, I'll do some investigation of why it wasn't saving your refresh token properly

**Comment by alexeiw123** [comment]
> Can you log in to the Tesla website with that account? Tesla often lock accounts if several failed login attempts occur, I've had to reset mine a number of times.

Yes, have just checked. Signed out and back in to be sure. Will need to wait on someone else to test to see if my email format is contributing.

**Comment by ngardiner** [comment]
Just tested this now

image

image

image

**Comment by ngardiner** [comment]
I also just realised how ugly the bright red prompt is in the login flow :) that is meant to be for error messages, I'll make it look a little nicer in an upcoming change

**Comment by alexeiw123** [comment]
I found the issue: my settings.json file still had old token information in it form when I changed the account password.
I did an `rm settings.json`, restarted the service and then MFA auth worked.

**Comment by ngardiner** [comment]
It wouldn't have been that. We only show the login box once we detect that either there is no existing token or the existing token is refused when we try to access the API. At that point they are effectively discarded and not used at all during the login process. 

The basic mechanics are: If you have a valid token you won't see a login box. If you see a login box, we use only the details you submit (the username and password) to validate your login and then obtain new tokens. There's no use case where the tokens should change when you change your password unless Tesla invalidates the login tokens at that point (which they likely do) but then we detect the API failure and go back to username/password auth to reobtain tokens and your existing tokens are not used.

So the tokens in the ```settings.json``` file are a red herring - we'll store your old expired token until we get a new one, but if they don't work we display a login box so you know to log in again.

**Comment by ngardiner** [comment]
There's also great importance to doing this. Tesla often has transient errors where they may refuse our token. If we just blanked the old token out and it turned out it was an issue with the auth handler and not your token, you'd not be able to log in again and your token would be blank so you'd have no access to the API at all.

Whereas in our approach, we keep the last used token until a new one is generated. If the issue was just with the auth flow on the Tesla side you wouldn't have been able to log in again to get new tokens but we'd still have held the old ones, so once things work again the prompt will disappear.

**Comment by alexeiw123** [comment]
The logic makes sense. I'm not sure why but deleting the settings.json and restarting the service worked. Tested immediately prior and after.

My steps prior to testing MFA where to:
1. change tesla account password (noting that Tesla API was working fine without MFA - car was plugged in at the time)
2. enable MFA on account
3. restart service to prompt log in
4. log in attempts resulted in error page (prior to your earlier MFA fix)
5. disable MFA, test, re-enable MFA
6. your fix is applied, log in returns error
7. delete settings.json
8. all fixed

I'm not sure which of these steps created the issue or if it can be recreated? step7. definitely resolved it for me.

**Comment by mikey4321** [comment]
@ngardiner - success:  

1) I updated to the latest main using git pull
2) I deleted settings.json
3) reboot the RPi and went to the web interface
4) This time my Tesla login details correctly went to the next screen with the MFA box (and red text - personally I would leave it like this so its very obvious that there is a 2nd step needed by the user)
5) web interface says success.
6) looking at the re-created settings.json all three of the API entries are now populated
7) so far so good - seems to be charging as expected, but won't be able to tell properly until this evening when it is supposed to stop cleanly

Thanks!

**Comment by ngardiner** [comment]
@alexeiw123 after some thought I may have discounted that the same patch that I updated earlier may have changed the behaviour of how we deal with detecting failed API tokens. I'll do some investigation and see if that's possibly what happened. MFA did not change this code but that patch changed code that is close enough to what you are describing that it *could* be responsible

@MikeBishop and I might need to review the ```car_api_available``` flow to see whether it continues to detect token issues accurately after the merge of #231

**Comment by alexeiw123** [comment]
@ngardiner good luck bug hunting. Would it be a value add to have a button in settings to remove any saved auth token details? It would be nice to have the option even outside of clearing or testing log in issues.

**Comment by ngardiner** [comment]
You can override the tokens today from the Settings menu. Just put any random value in there and it will override the settings. I wouldn't see adding another option to clear them being necessary - I'm not even a fan of the manual entry to be honest. No flow should ever require this - we've stored tokens the same way for the past 2 years and even with MFA flow they haven't changed, the only thing that has changed is API error handling and *if* it was a bug then we'll just get it fixed and we shouldn't see it again as we haven't until now.

**Comment by alexeiw123** [comment]
> You can override the tokens today from the Settings menu. Just put any random value in there and it will override the settings

Ah good to know.
philosophies of the flow make sense too

**Pull request merged**
