### PR TITLE
EMS Module for P1 Monitor

### PR DESCRIPTION
**Pull request by mvaneijken**
Hereby a new module based on the [P1 Monitor](https://www.ztatz.nl/), which is a Energy Monitoring tool running on a RaspberryPI that reads messages from the P1 port from a [smart meter](https://en.wikipedia.org/wiki/Smart_meter). It has a API which can be used by TWCManager using this module.

Before determining to accept this pull request, there are some questions:
1. The P1 Monitor API provides values per phase. In my case I have 3. I'm not sure how TWCManager is interpreting this information. To avoid overloading one or more phases this module reports the maximum value of the phase has the highest load. To avoid acting on spikes it takes the [trimmed mean ](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.trim_mean.html) of a configurable amount of samples from the P1 Monitor API and reports the maximum value back to TWCManager. Is the the correct way to report the consumption values to TWCManager?
2. Same counts for the generated power, there it will take the same trimmed mean per phase as above. Difference is that it will sum up the values in the assumption that it will never overload the main fuse. When it would the PV installation is not installed according the regulations.  Above of that, the TWC should also have a correct max amount of amps configured in the generic config. Is the the correct way to report the generation values to TWCManager?
3. I'm still interpreting the policy module, but here some examples on how I understood it. Is that expected when integrating with TWCManager?: 

**Example 1: Only consumption**
Phase1 Consumption Trimmed Mean: 5200W
Phase2 Consumption Trimmed Mean: 1700W
Phase3 Consumption Trimmed Mean: 2300W
Phase1 Generation Trimmed Mean: 0W
Phase2 Generation Trimmed Mean: 0W
Phase3 Generation Trimmed Mean: 0W

**Reported to TWCManager:
consumedW = 5200W
generatedW = 0W**

_Expected result when using solar plus charging, it will charge the car only on the minimum value._

**Example 2: Only generation**
Phase1 Consumption Trimmed Mean: 0W
Phase2 Consumption Trimmed Mean: 0W
Phase3 Consumption Trimmed Mean: 0W
Phase1 Generation Trimmed Mean: 1000W
Phase2 Generation Trimmed Mean: 900W
Phase3 Generation Trimmed Mean: 100W

Reported to TWCManager:
**consumedW = 0W
generatedW = 2000W**

_Expected result when using solar plus charging, it will charge the car at 2000W._

**Example 3: Generation and consumption** 
Little explanation: The P1 of the Smart Meter reports a substracted generation value from consumption. So when generating 1000W on Phase 1 and consuming 500W on Phase 1, it will report 500W of generation. When generating 500W and consuming 1000W it will report 500W of consumption.
Phase1 Consumption Trimmed Mean: 1000W
Phase2 Consumption Trimmed Mean: 0W
Phase3 Consumption Trimmed Mean: 500W
Phase1 Generation Trimmed Mean: 0W
Phase2 Generation Trimmed Mean: 1000W
Phase3 Generation Trimmed Mean: 0W

Reported to TWCManager:
**consumedW = 1000W
generatedW = 1000W**

_Expected result when using solar charging, it will charge the car at 1000W, and wil have some additional consumption on the 
phases 1 and 3._

**Example 4: Generation at 16 Amps (for 230V):** 
Phase1 Consumption Trimmed Mean: 0W
Phase2 Consumption Trimmed Mean: 0W
Phase3 Consumption Trimmed Mean: 0W
Phase1 Generation Trimmed Mean: 3680W 
Phase2 Generation Trimmed Mean: 3680W
Phase3 Generation Trimmed Mean: 3680W

Reported to TWCManager:
**consumedW = 0W
generatedW = 11040W**

_Expected result when using solar plus charging, it will charge the car at 16 Amps._

**Example 5: Generation at 16 Amps (for 230V), and consumption at 16 Amps for two phases.** 
Phase1 Consumption Trimmed Mean: 3680W 
Phase2 Consumption Trimmed Mean: 3680W 
Phase3 Consumption Trimmed Mean: 2000W 
Phase1 Generation Trimmed Mean: 3680W 
Phase2 Generation Trimmed Mean: 3680W
Phase3 Generation Trimmed Mean: 3680W

Reported to TWCManager:
**consumedW = 3680W 
generatedW = 11040W**

_Expected result when using solar plus charging, it will charge the car at 16 Amps._

So, although there are some questions from my side, I'd love to hear what you think of this.

### CODE REVIEW

**Comment by mvaneijken** [comment]
Update: I tried to test it using the dummy connector, but that one seem to give some warnings I cannot explain, but I don't think that this is something this EMS module is causing: 
Before starting the charge, the values are as follows:
image

When started the charge at 16 Amps it reports:
```
10:56:16 TWCManager 20 Limiting charging to 16.00A.
10:56:16 TWCManager 20 Charge when above 12A (minAmpsPerTWC).
10:56:17 TWCSlave   20 WARNING: Offering slave TWC 4142 16.0A instead of 21.0A to avoid overloading wiring shared by all TWCs.

```
The settings are as follows:
```
wiringMaxAmpsAllTWCs = 16
wiringMaxAmpsPerTWC =16
minAmpsPerTWC = 12 
defaultVoltage = 240 
numberOfPhases = 3
greenEnergyFlexAmps = 0
useFlexAmpsToStartCharge = false
subtractChargerLoad = true
```

**Comment by mvaneijken** [comment]
Update: Tested the EMS module on a Raspberry PI Zero W and it seems to works fine:
image

**Comment by ngardiner** [comment]
Looking great, @mvaneijken! Let me know when you think I should merge this, if it's in the next day or two we can include it in release v1.2.3 :)

**Comment by mvaneijken** [comment]
Thx @ngardiner! I would say, merge it with 1.2.3. It works fine in my environment.

**Pull request merged**
