### PR TITLE
fix for favicon

### PR DESCRIPTION
**Pull request by hopfi2k**
include TWCManager version number to always use up-to-date favicon

### CODE REVIEW

**Comment by ngardiner** [comment]
Cool! our first Modbus EMS implementation - how's it working for you? I know there may be some other inverters out there where Modbus would be useful as an interface - I wonder how much standardisation there is across implementations?

Great contribution, great documentation, thanks! Let me know if you're ready to merge and I'll hit the button

**Comment by hopfi2k** [comment]
Hi there,

I‘m using this for the past 4 months without problems. Just did some code cleanup yesterday before making the pull request ;-) Please feel free to merge it.
ModBus is relatively straight forward, so supporting other ModBus inverters should only require to change the register addresses. If you know some other inverters or meters that you think should get supported, please let me know, and I‘ll see what I can do.

Best regards 
Andy


Von meinem iPhone gesendet

**Comment by ngardiner** [comment]
Excellent, in fact I do have one implementation in mind. Paging @Der-Kieler, thanks to @hopfi2k we now have a module which does EMS over ModBus, I recall you're doing the same using openWB which then integrates with TWCManager, this might be a way to implement direct ModBus integration with SolarEdge to avoid having to go between the two. It looks like we'd need to know the registers that openWB are polling however.

**Comment by hopfi2k** [comment]
This should be relevant: https://openwb.de/main/wp-content/uploads/2020/10/ModbusTCP-openWB.pdf
Questions are:
- what do we want the TWCManager do with OpenWB?
- should OpenWB control the TWC or TWCManager the OpenWB?
- is having an OpenWB and a TWC in the same network (household) really a common use case?

**Comment by MikeBishop** [comment]
A new EMS is pretty cool, but I question having it in the same PR as a favicon location fix.

**Comment by Der-Kieler** [comment]
@hopfi2k:

A lot of people are using the TWCM for years together with openWB! Most of them uses the draconvention fork, as it was the first one.
openWB is very powerful and has a lot of features, which TWCM not have (today). Like Solaredge Support by modbus for example. openWB supports many inverters, wallboxes and other stuff. 
In this use case the TWCM is the "virtual "frontend" for the TWC and works in the background cmmunicating with openWB. I don't see the TWCM when using openWB, but without TWCM we couldn't use the TWC. So the TWCM is absolutely necessary in this use case
Connection is working through the old html-Interface (as other projects). As long as this part of TWCM stays alive everything is fine for me and all the other projects and people.

The only pitty is, that we have two programs (and two Raspberry Pi's) beeing neccessary to solve this use case. Surely it would be great to have only one program (TWCM), but I feel, that this will be a long way for TWCM to have all the features openWB has today.
I would say: Give openWB a try, but it's only available in german up to now.

**Comment by hopfi2k** [comment]
Thanks for the explanation. I have looked into the SolarEdge ModBus thing (Sunspec protocol). Should be no big deal to create a SolarEdge ModBus EMS module. Does anyone have a SolarEdge inverter with ModBus who would be willing to test such an EMS module?
Furthermore openWB has a stunning set of features, but some of them are bound to the openWB hardware. I don't think that TWCM should try to mimic the openWB functionality as it is a different product. Maybe we should consider creating some feature requests for TWCM to get an idea, what is high on the priority list that people want and probably need?

**Comment by Der-Kieler** [comment]
A copy of openWB doesn't make sense. I think so, too.
openWB has two parts: Complete Wallboxes with HW and SW and secondly the open source project of the software. The company has their own software developer and together with others working on the project they have a lot of man power.
But: It's only availabe in german! So a complete solution in english is not that stupied.
Today, I think most users are using TWCM in their smart home projects and have programmed their own frontends or integrated it in existing. 
My 2Cents.

**Comment by ngardiner** [comment]
There's no suggestion that we would replicate openWB's logic, only that we could query via ModBus without requiring openWB as an external dependency and without reliance on the interface between openWB and TWCManager which is from my observation workable but not optimal.

At the very least, it would be nice for owners to be able to see generation and consumption details in TWCManager and use them in charge policy, something that can't be achieved currently with openWB in between.

Anyway it does seem that this will be the extent of the implementation for now but its great to have a template going forward - thanks @hopfi2k

**Comment by Der-Kieler** [comment]
Hey!

Is it possible to get the information generation and consumption? Indeed, this is a missing point for me in openWB.
openWB takes over these informations for other wallboxes but TWC manager doesn't deliver these informations.

Would be absolutely great if it is possible to show and delvier these informations. :-)

**Comment by hopfi2k** [comment]
If I understand this right, we would need to implement a ModBus Server into TWCM to provide these informations to others (like OpenWB)? While this would be possible in general, we maybe should discuss this in a separate future request?

**Comment by ngardiner** [comment]
No, we've only discussed directly querying the SolarEdge inverter instead of relying on openWB to do it. I'm not sure why but the suggestion of openWB appears to have given you the impression that we're doing anything to do with openWB at all. We are not. Currently TWCManager has no native capability to directly query the SolarEdge inverter (which is a ModBus TCP interface). For this reason, people would need to rely on an external interface _such as_ openWB to query the inverter instead of TWCManager. This leads to added complexity and loss of functionality. I am suggesting querying SolarEdge directly as you have for your interface by querying the registers relevant for SolarEdge inverters.

For the removal of all doubt, nothing here involves replacing openWB's functionality, integrating with openWB or otherwise. This is simply a suggestion to implement ModBus TCP querying as an alternative to the current SolarEdge API interface which is significantly hampered by the API's query rate limitations.

**Comment by hopfi2k** [comment]
My bad, sorry for the misunderstanding. Creating a SolarEdge ModBus EMS shouldn't be a big deal. I should find some time to work on it in the next few days. Since I don't have a SolarEdge inverter, is there someone who has one and would be willing to it?

**Comment by Der-Kieler** [comment]
@hopfi2K: I have a SolarEdge Inverter and can test it (at the moment I'm happy with the combination of openWB and TWCM and stay there for productiv use, but for testing I will set up another SD-Card).
I'm not that good in Linux, so you have to be a little bit patient with me testing it. :-)

**Comment by hopfi2k** [comment]
Thanks very much! I'll ping you, once I have a prototype ready for testing

**Pull request merged**
