### PR TITLE
Returns 0 for consumption and not generation value

### PR DESCRIPTION
**Pull request by dschuesae**

### CODE REVIEW

**Comment by MikeBishop** [comment]
Yes, this looks like a net improvement.  Perhaps an explicit zero with a comment that SolarEdge only allows reporting generation, not consumption, would be clearer though?

**Comment by dschuesae** [comment]
Completely agree. I read the .md file and there you find it (but only because it only generation value is mentioned ;-) ).

**Comment by GMerg** [comment]
Depending on how your solar-system is build, you also get the power consumption in the normal API call. Mine simply doesn't provide that as it's not build with that. Im sure it would be easy to add all that if you @Der-Kieler would provide the paramaters to add support for it.

**Comment by ngardiner** [comment]
Yes, just looking at the OpenHAB binding that @Der-Kieler linked to now. Let me see what I can work out. I'm a bit surprised that the implementation for OpenHAB needs a manual switch to indicate a metered installation, let's see if it's something we can automatically detect because I'm not a fan of having to specify manually to poll for the value if we can avoid it.

**Comment by dschuesae** [comment]
It's not the direct api call to the local solar edge inverter. So I'm sure there is an extra path over another local tool.

**Comment by Der-Kieler** [comment]
Wow! So great, that you look at it! Thanks a lot!
Do You know OpenWB (Open Wallbox)? They also read out the data of SolarEdge, but they do it localy, instead of using the API.
I know that this would be a complete redesign, but perhaps a longtearm possibility:
https://github.com/snaptec/openWB/blob/master/modules/bezug_solaredge/solaredge.py
OpenWB have a lot of other interfaces, perhaps this helps in other cases, too.
I'm not a programmer and not very familiar with Linux, but I will help you testing, if possible. :-)

**Comment by ngardiner** [comment]
> Do You know OpenWB (Open Wallbox)?

Oh interesting, just had a quick look. Looks like they talk to the meter directly over Modbus. I will admit to being pretty uninformed when it comes to modbus but I could see potential for it to be an option for communicating with energy/meter systems in meter boxes. I'll do some more reading to understand the hows and why's of modbus integration.

**Comment by Der-Kieler** [comment]
They eaven have an integration for TWCManager and a very nice frontend, visualising the different data. You can buy a whole Wallbox from them: Nice but expansive.
AnywayI don't want two Raspberries for one issue (loading my car by sun). So I stay with the TWCM.

**Comment by Der-Kieler** [comment]
O.K., these are the things I found out:

I get values in Current Consumptionm but they are no true: I have 6,7KW and in TWCM it shows 3.00 watts!
I thought that the shown values have to be multiplied by thousand, because the delivered data is in KW and you import them as watts. But this seems to be not true, also.
Fact is: Both values don't fit! Perhaps you take the wrong variables from the API?
SolarEdge API is not real time. I have read something of every 15 minutes and a limited number of calls per day. But I don't know if this is true. Makes it eaven harder to understand the values at all. Would be better to take data directly from the converter, as for example OpenWB (Open Wallbox - another project on GitHub) does.
Sorry, I tried now for nearly 2 hours and it's still not clear for me what has to be corrected.

**Comment by ngardiner** [comment]
Cross-checking with the SolarEdge API spec and with the OpenHAB binding, we're both reading the same real-time value, however OpenHAB is doing something additional that I am not, it is checking the unit of measurement. It may be that your value is actually expressed in a different unit. To determine if this is the case, I've added a check for the reported unit to see if it is Watts or not, and if not it will report an error at debugLog level 1 (to make seeing it easy without having to increase debugLog value). Could you please ```git pull``` again, and restart TWCManager, and then look for a message starting with:

```Unknown SolarEdge Consumption Value unit:```

And let me know what unit of measurement is indicated? If you don't see that message and you continue to see a small number of watts logged for consumption, it suggests that the value we're reading is in W and that the issue might be elsewhere.

**Comment by Der-Kieler** [comment]
Hey!

I’m not at home. Back again in about 4 hours. I’ll check it than.

Lorenz

Mit freundlichen Grüßen

Lorenz Roth

Gesendet von unterwegs.
________________________________
Von: Nathan Gardiner <notifications@github.com>
Gesendet: Saturday, September 26, 2020 11:08:30 AM
An: ngardiner/TWCManager <TWCManager@noreply.github.com>
Cc: Der-Kieler <lorenz.roth@live.de>; Mention <mention@noreply.github.com>
Betreff: Re: [ngardiner/TWCManager] Returns 0 for consumption and not generation value (#145)


Cross-checking with the SolarEdge API spec and with the OpenHAB binding, we're both reading the same real-time value, however OpenHAB is doing something additional that I am not, it is checking the unit of measurement. It may be that your value is actually expressed in a different unit. To determine if this is the case, I've added a check for the reported unit to see if it is Watts or not, and if not it will report an error at debugLog level 1 (to make seeing it easy without having to increase debugLog value). Could you please git pull again, and restart TWCManager, and then look for a message starting with:

Unknown SolarEdge Consumption Value unit:

And let me know what unit of measurement is indicated? If you don't see that message and you continue to see a small number of watts logged for consumption, it suggests that the value we're reading is in W and that the issue might be elsewhere.

**Comment by Der-Kieler** [comment]
Hello ngardiner!

I just made the git pull, changed the debug level back to 1 in config.json and restartet the Pi.
I haven't got the message and the watts are still not correct.

At the moment I have a current Generation of 741watts. But this is definetly wrong, because it's nearly dark outside and it's strong rain. In the SolarEdge App I have 0 kw Generation!
Current consumpiton stay at zero and the house uses round about 800 watts.

The data is updated every 5 minutes by SolarEdge. I have stopped time. So it's difficult to see waht happens.

At the next cycle I have now zero Consumption and zero Generation?!
I think the API is not working well or something else is wrong. - I don't understand it. :-/

If you still want to figure out the issue, I have an idea: I have published my solar data on a Solar Edge Portal (https://monitoringpublic.solaredge.com/solaredge-web/p/site/public?name=PV-Lorenz&locale=en_US#/dashboard). And also I can give you my API Key. - I don't think that it can be missused, because one can only read data. 
You can than setup your own TWCManager and compare the data with the portal directly. What do you think? :-)

**Comment by ngardiner** [comment]
Hi @Der-Kieler, thanks for that. I've added a new debugMode option for SolarEdge which should give me the details I need, as it will log all of the requests and responses from the API. Note that this will include the API Key so best not to paste anything publicly, instead I can give you a way to upload the log just to me, and I'll take a closer look. Appreciate all of your help so far tracking down the issue, if you could drop me an email at ```ngardiner@gmail.com```, I'll send you all of the details.

**Comment by Der-Kieler** [comment]
Hello!

Please respond to Lorenz.Roth@live.de.

Lorenz

Mit freundlichen Grüßen

Lorenz Roth

Gesendet von unterwegs.
________________________________
Von: Nathan Gardiner <notifications@github.com>
Gesendet: Sunday, September 27, 2020 8:52:45 AM
An: ngardiner/TWCManager <TWCManager@noreply.github.com>
Cc: Der-Kieler <lorenz.roth@live.de>; Mention <mention@noreply.github.com>
Betreff: Re: [ngardiner/TWCManager] Returns 0 for consumption and not generation value (#145)


Hi @Der-Kieler<https://github.com/Der-Kieler>, thanks for that. I've added a new debugMode option for SolarEdge which should give me the details I need, as it will log all of the requests and responses from the API. Note that this will include the API Key so best not to paste anything publicly, instead I can give you a way to upload the log just to me, and I'll take a closer look. Appreciate all of your help so far tracking down the issue, if you could drop me an email at ngardiner@gmail.com, I'll send you all of the details.

**Pull request merged**
