### PR TITLE
allow serving of static files

### PR DESCRIPTION
**Pull request by hopfi2k**
this pull request enables serving of static (local) content throught the buildin http-server from the ./lib/TWCManager/Control/static/ directory

### CODE REVIEW

**Comment by MikeBishop** [comment]
Have you tested that this doesn't allow retrieving, i.e. `static/../../sensitive.json`?  Whatever number of uplevels is required to grab the `settings.json` file with the tokens, for example?

**Comment by hopfi2k** [comment]
Good catch @MikeBishop  - will check and address if necessary!

**Comment by hopfi2k** [comment]
I have done further testing and it doesn't seem, that you can't retrieve sensitive files. Nevertheless I'll add some safety precautions in a future PR. Thanks again for pointing out this possible problem @MikeBishop

**Comment by hopfi2k** [comment]
@ngardiner I tested my PR for severing static files as thoroughly as I could but wasn't able to find any security holes the way I implemented it. If you won't mind this PR can be merged - at least from my side. Thx!

**Comment by ngardiner** [comment]
Looks good to me, thanks!

**Pull request merged**
