### PR TITLE
Clean up /api/getSlaveTWCs

### PR DESCRIPTION
**Pull request by jherby2k**
edited changes:

1) Don't round total reportedAmpsActual. The individual TWC values aren't rounded.

1) total maxAmps for all TWCs shouldn't be additive.

1) Add total carsCharging

1) reordered recent additions alphabetically

### CODE REVIEW

**Comment by ngardiner** [comment]
getSlaveTWCs is used by the web interface, so this would indeed be a breaking change unless the web interface were updated too. I would not necessarily recommend aligning the API calls to the HASS status module, the HASS status module is much older than the API spec, there's likely been many learnings inbetween.

maxAmps is always 80 for you because that's what your TWC supports as a maximum :) For me, it's 32. It definitely has a purpose, we use it to render the maximum value for chargeNow and to provide contextually appropriate amp selections where necessary.

**Comment by jherby2k** [comment]
1. I will revert reportedAmpsMax back to lastAmpsOffered, if you prefer that convention.

3. I don't think that's true. The value rendered looks like its using maxAmpsToDivideAmongSlaves from getStatus. I get 32, not 80. Which makes sense because if you let me set it to 80 i'd blow the breaker (32 is my wiring max as per config.json). My change works fine in the UI.

I should update test_chargeNow.py as well, provided you're okay with the above.

**Comment by ngardiner** [comment]
> regarding maxAmps, I don't think that's true. The value rendered looks like its using maxAmpsToDivideAmongSlaves from getStatus. I get 32, not 80. Which makes sense because if you let me set it to 80 i'd blow the breaker (32 is my wiring max as per config.json). My change works fine in the UI and I can see no other references to maxAmps in the code.

You're confusing two different values here

   * maxAmps is a value that is tied to the physical TWC hardware. A North American v2 TWC has an 80 amp limit whilst a European v2 TWC has a 32 amp maximum. This is basically the same as telling you what the largest number is on the rotary switch. It is the hardware supported maximum, it does not know anything about your electrical structure.

   * maxAmpsToDivideAmongSlaves is from a config parameter, it is software based and is set by the owner based on the breaker size.

We may not exceed either of those two values for any TWC, but we may not exceed the second value for all slaves combined.

**Comment by jherby2k** [comment]
I get that maxAmps is the hardware value, even though the name sux. I'm telling you that it isn't used by the UI. Anyway, i'll put it back if you think its useful to someone.

**Comment by ngardiner** [comment]
What do you think it should be called?

**Comment by jherby2k** [comment]
maxAmpsByHardware? maxAmpsConfigurable?

Also maxAmps is (was) summed for the total, so i should change that to min() - If you have two TWCs, one 80 and one 32, total maxAmps should be 32, not 112 right? or does a total maxAmps not make sense at all?

**Comment by ngardiner** [comment]
> maxAmpsByHardware? maxAmpsConfigurable?

What is maxAmpsConfigurable - the wiring max for all or per TWC? How are you going to work out which of those values to represent? Other than being a significantly more convoluted name than maxAmps in the context of a TWC (as this is the output of the showSlaveTWCs command - it's giving you the state of the TWC as reported by the device itself. All of the values you're looking at - whether it be max wiring amps for all TWCs or per TWC, are not per device values and don't belong in the showSlaveTWCs table, it didn't come from a slave TWC. We are representing what we have been told by the slave TWC that it supports.

If you want config values, they come from getConfig, and they're represented once - because they aren't per TWC

> Also maxAmps is (was) summed for the total, so i should change that to min() - If you have two TWCs, one 80 and one 32, total maxAmps should be 32, not 112 right? or does a total maxAmps not make sense at all?

All of these values are useful, because these are API calls which can be used to interface with other systems to make judgements or call functions. I'm challenging your logic of removing a single thing without a good reason to do so. If we know the capability of the TWC because we communicate with it I see no reason not to make that information available to external systems - this is effectively a regression

Also, going back to your earlier comment

> I'm telling you that it isn't used by the UI. Anyway, i'll put it back if you think its useful to someone.

It is, in lib/TWCManager/Control/themes/Default/showStatus.html on lines 88 and 109, and the PR contained no cleanup for those fields, meaning your PR would break the interface and whilst my guess of where it was used was wrong - it's simply a requirement that you do your best to check you don't break anything when you submit a PR. Instead you've expected me to check this for you? I've already made my case in your other thread for why I feel all of this is a waste of the limited amount of development time I have on a weekly basis, to challenge the unnecessary removal of values from the API call just based on your sole opinion of the validity.

I appreciate any and all contributions but it doesn't mean they'll be merged without further discussion. A PR which comes along and breaks UIs, removes values that were previously published and therefore may be in use by people because you don't consider them to be worthwhile... you can see why I'm pushing back.

**Comment by jherby2k** [comment]
I'm okay with pushback, and sorry if you feel like i'm wasting your time. Apologies for missing that html doc in my search.

Can you comment on this please?

"If you have two TWCs, one that supports 80 and one that only supports 32, total maxAmps should be 32, not 112 right?"

**Comment by jherby2k** [comment]
I'm going to squash and re-submit.

**Pull request closed without merging**
